services:
  spectra-stem:
    image: spectra_stem:latest
    command: ["python3", "app.py"]
    build:
      context: .
      dockerfile: ./Dockerfile
    expose:
      - "7860:7860"
    volumes:
      - "./output/:/root/spectra/output/"
      - "./bin/:/root/spectra/bin/"
