services:
  spectra-stem:
    image: spectra_stem:latest
    build:
      context: .
      dockerfile: ./spectra/services/audio/audio.Dockerfile
    expose:
      - "7860:7860"
    volumes:
      - "./output/:/root/spectra/output/"
